### ISSUE TITLE
Can you please explain usage of field trees in the code ?

### ISSUE THREAD

**Issue by anuragvohraec** [Alex-Werner/SBTree#11]
Hi Alex,

I was going through this code and was finding difficulty in understadng it.
Can you please explain me the usage of SBFtree specifically?
If you have /can provide a relation diagram between this various components : SBTree, SBFTree, SBFLNode, SBFRoot and SBFLeaf, it will be really helpfull for undertading the entire code quite quicker.
A basic design of this code will be much appriciated.

**Comment by Alex-Werner** [comment]
Hi ! 

It's basically to segregate the different parts. 
The goal for me is a DB that with the help of B+ Tree is able to handle storing in FS and deal with indexing to improve the speed of finding elements. (You can see it here : https://github.com/Alex-Werner/TyrDB)
Therefore here is the logic, I will provide a schema but for now let me at least explain : 

SBTree : It's just an instance of the lib. Dealing with the basics options such as adapters, fields etc... 
SBFTree : The F stands for Field, as each field would be indexed separately. It deals with finding, creating etc... along with setting a SBFRoot. 

To better understand SBFRoot and SBFLeaf, it is better for me to share this link with you : https://www.cs.usfca.edu/~galles/visualization/BPlusTree.html that help on the visualisation of what the tree look like.
 
SBFRoot : In a BTree, the root represent the uppermost element in the visualization I've shared, this class is made to know which side to go down in the leaf in order to find the elements requested.
SBFLeaf : It's all the leaf of the tree, they hold the information and therefore that's where most of the findGreater/findLower methods are. 

There is a fixture that might help : https://github.com/Alex-Werner/SBTree/blob/master/test/fixtures/snapshots/snapshot.1.1.json 

In the mean time, in order to consider this issue handled for closure here is the missing part I need to work on (for reference) : 

- Documents the structure of the project
- Provide you with a design document (it will be probably be a diagram (Activity Diagram would do the job I hope)

**Comment by anuragvohraec** [comment]
> There is a fixture that might help : https://github.com/Alex-Werner/SBTree/blob/master/test/fixtures/snapshots/snapshot.1.1.json

> In the mean time, in order to consider this issue handled for closure here is the missing part I need to work on (for reference) :
> * Documents the structure of the project
> * Provide you with a design document (it will be probably be a diagram (Activity Diagram would do the job I hope)

Perfect!
Thank you this is helpfull.

Cheers!
